#!/usr/bin/env bun
// 6nz state seam — the lightweight digest generator for the vPA deputy (Function 1).
//
//   bun scripts/state.ts --digest   → (re)write handOffs/digest.md  (deputy owns this, per-tick)
//   bun scripts/state.ts --check    → print `current` | `STALE`     (PA session-start freshness guard)
//
// Design (mirrors scrml's state.ts contract, scaled to 6nz's thin surface):
//  - Projects MACHINE-TRUTH only (HEAD · playground inventory · dogfood scrml SHA · maps-staleness ·
//    recent changelog sessions · flogence-intake count). The bug board is PROSE (master-list §F) — the
//    digest POINTS to it rather than parsing it (projecting prose reintroduces the drift the digest fights).
//  - Freshness is SOURCE-based (the digest's own file never stales itself — no ouroboros): STALE iff any
//    projected SOURCE is newer than handOffs/digest.md.
//  - No deps; node: builtins only (bun-compatible).

import { execSync } from "node:child_process";
import { readdirSync, readFileSync, statSync, existsSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const DIGEST = join(ROOT, "handOffs", "digest.md");

function sh(cmd: string): string {
  try { return execSync(cmd, { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] }).toString().trim(); }
  catch { return ""; }
}
function mtime(p: string): number { try { return statSync(p).mtimeMs; } catch { return 0; } }
function walkNewest(dir: string): number {
  if (!existsSync(dir)) return 0;
  let newest = 0;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name === "dist" || e.name === "node_modules") continue;
    const p = join(dir, e.name);
    newest = Math.max(newest, e.isDirectory() ? walkNewest(p) : mtime(p));
  }
  return newest;
}

// --- the projected SOURCE set (anything newer than the digest => STALE) ---
function sourceNewest(): number {
  return Math.max(
    walkNewest(join(ROOT, "src")),
    walkNewest(join(ROOT, ".claude", "maps")),
    mtime(join(ROOT, "docs", "changelog.md")),
    mtime(join(ROOT, "master-list.md")),
    mtime(join(ROOT, "handOffs", "delta-log.md")),
    mtime(join(ROOT, "handOffs", "flogence-intake.md")),
    mtime(join(ROOT, "hand-off.md")),
  );
}

// --- projections ---
function playgrounds(): string[] {
  const src = join(ROOT, "src");
  if (!existsSync(src)) return [];
  return readdirSync(src, { withFileTypes: true })
    .filter(e => e.isDirectory() && e.name.startsWith("playground-"))
    .map(e => {
      const d = join(src, e.name);
      const tags = ["app.scrml", "test.js", "bridge.js"].filter(f => existsSync(join(d, f)));
      return `${e.name} [${tags.join(" ")}]`;
    });
}
function dogfoodSha(): string {
  const s = sh("git -C ../scrml rev-parse --short HEAD");
  return s || "(scrml repo not resolvable from here)";
}
function recentSessions(): string[] {
  const cl = join(ROOT, "docs", "changelog.md");
  if (!existsSync(cl)) return [];
  const heads = readFileSync(cl, "utf8").split("\n")
    .filter(l => /^##\s+(Session|S)\s*\d|^##\s+S\d/i.test(l))
    .map(l => l.replace(/^#+\s*/, "").trim());
  return heads.slice(0, 5);
}
function flogenceIntake(): number {
  const f = join(ROOT, "handOffs", "flogence-intake.md");
  if (!existsSync(f)) return 0;
  return (readFileSync(f, "utf8").match(/NEW flogence bug/g) || []).length;
}
function mapsStale(): boolean {
  return walkNewest(join(ROOT, "src")) > walkNewest(join(ROOT, ".claude", "maps"));
}

function buildDigest(): string {
  const head = sh("git rev-parse --short HEAD") || "(no git)";
  const pgs = playgrounds();
  const intake = flogenceIntake();
  return `<!-- @digest head=${head} generated by scripts/state.ts --digest -->
# 6nz — session-start digest (@generated · asserted, not verified)

> Read at session-start ONLY if \`bun scripts/state.ts --check\` reports \`current\`. If \`STALE\` or absent,
> DISTRUST this and read the authoritative files cold (a drifted digest is worse than reading cold).
> Every line below is a PROJECTION (asserted), never a verification.

- **HEAD:** ${head}
- **Dogfood scrml build:** ${dogfoodSha()}
- **Playgrounds (${pgs.length}):**
${pgs.map(p => `  - ${p}`).join("\n") || "  - (none)"}
- **Maps:** ${mapsStale() ? "**STALE** — src newer than .claude/maps (PA: cast a (vpa:) maps refresh)" : "current"}
- **Recent sessions (changelog):**
${recentSessions().map(s => `  - ${s}`).join("\n") || "  - (none)"}
- **Flogence intake:** ${intake === 0 ? "empty" : `**${intake} bug(s) queued** → handOffs/flogence-intake.md (PA: triage → §F)`}

### Pointers (NOT projected — read the source)
- **Bug board:** \`master-list.md §F\` (prose — open bugs / ledger; the digest does not parse it).
- **In-flight + open questions:** \`hand-off.md\` (top section).
- **Deputy state:** \`handOffs/deputy-state.md\` (ACK + heartbeat).
`;
}

const arg = process.argv[2];
if (arg === "--digest") {
  writeFileSync(DIGEST, buildDigest());
  console.log(`wrote ${DIGEST}`);
} else if (arg === "--check") {
  if (!existsSync(DIGEST)) { console.log("STALE"); process.exit(0); }
  console.log(sourceNewest() > mtime(DIGEST) ? "STALE" : "current");
} else {
  console.log("usage: bun scripts/state.ts --digest | --check");
  process.exit(1);
}
